### PR TITLE
#2287: Update to latest stable 2022.02.xx

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
- The Mapstore submodule has been updated to latest stable of **2022.02.xx** from **2022.01.xx**
- The application specific config are retained and adjusted wherever applicable

## Issue

- https://github.com/geosolutions-it/support/issues/2287

### CODE REVIEW

**Comment by tdipisa** [comment]
@MV88 can you please schedule the review for tomorrow?

**Comment by MV88** [comment]
> @MV88 can you please schedule the review for tomorrow?

on it

**Review by MV88 — CHANGES_REQUESTED** [review]
Hi @dsuren1 

- [x] can you fix a lint issue in here --> webpack.config.js since there is an extra comma
image


- [x] trying to edit a context, it crashed at second step
image
- [x] have found some issues on holding the login session, see here 

https://user-images.githubusercontent.com/11991428/196385609-bdf70997-d430-4340-b05f-9fed2d163274.mp4

- [x] it is possible to add widgets on a public dashboard as anonymous user
image

- [x] I have found some weirdness on crating charts, sometimes i get back some NaN, plus i ws not able to generate a valid chart, missing some info on which attributes or layers use

https://user-images.githubusercontent.com/11991428/196390274-93673275-18d3-453c-b534-070eb6bd663f.mp4

- [x] trying to add a layer from this service will result in nothing happening

image

- [x] in console while opening toc item settings display tab I have this error 
image


- [x] can we include import/export for dashboard and geostory?

@dsuren1 
please check that session problem, otherwise i cannot test completely the upgrade

**Comment by dsuren1** [comment]
@MV88 
Thanks for the review. 

> * [ ]  trying to edit a context, it crashed at second step
>   image

Not sure how it wasn't occuring before. Anyway, I have added a plugin config for CRSSelector with filterAllowedCRS. This fixes the issue

> * [ ]  have found some issues on holding the login session, see here

Reason being latest service is not available in DEV instance hence call to `refreshToken` fails with 405

> * [ ]  it is possible to add widgets on a public dashboard as anonymous user

Because of this condition https://github.com/geosolutions-it/MapStore2/blob/2022.02.xx/web/client/selectors/dashboard.js#L22 , in austrocontrol `isNaN(path.substr(-4))` resolves to true for ex: [`/dashboard/51`](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/dashboard/51) due to the id length being 2. This behavior is existing in DEV Austro. This may need to be handled in Mapstore.

> * [ ]  I have found some weirdness on crating charts, sometimes i get back some NaN, plus i ws not able to generate a valid chart, missing some info on which attributes or layers use

Could be the because of the session issue. I tried with gs-stable and found no issues. Also I tried with the layer used in the clip and below is the behavior, which matches the DEV
image

> * [ ]  trying to add a layer from this service will result in nothing happening

I tried adding from `https://sdigeo-free.austrocontrol.at/geoserver/tn-a/wms` and I was able to add layers. I'm not able to access the `https://sdimd-free.austrocontrol.at/geonetwork/csw-inspire/eng/csw` even in DEV.

> * [ ]  can we include import/export for dashboard and geostory?

Added

**Review by MV88 — CHANGES_REQUESTED** [review]
@dsuren1 please tick the things addressed by the PR

- [x] Also i see this has not been checked

> in console while opening toc item settings display tab I have this error

on my second review i have found these stuff, but maybe they are pre existing issues

- [x] opacity color is not persisted for contexts 

https://user-images.githubusercontent.com/11991428/196648495-3af1f3e5-4944-4e60-81b9-2234d213b308.mp4

- [x] state of context is persisted when editing back the context
 
https://user-images.githubusercontent.com/11991428/196648531-3f20029a-eb4e-44a3-830a-b134c69a65d0.mp4

- [x] plugins configs needs to be checked, as this step has been missed

image


other than this the rest seems ok

**Comment by dsuren1** [comment]
@MV88 

> > in console while opening toc item settings display tab I have this error

Seems to be happening in **Mapstore** too. Possibly due to missing msg params and maybe it's intentional to display the message as an example
```
"templateFormatInfoAlertExample": "The id of the feature is <span style='white-space:nowrap'>${ properties.id }</span> or <span style='white-space:nowrap'>${ properties['data-value'] }</span>",
```
image


> on my second review i have found these stuff, but maybe they are pre existing issues
> 
> * [ ]  opacity color is not persisted for contexts

> * [ ]  state of context is persisted when editing back the context

You are right. these behaviour seems to be existing in **Mapstore**

**Review by MV88 — APPROVED** [review]

**Comment by tdipisa** [comment]
> in console while opening toc item settings display tab I have this error

I don't see any error to ne honest guys

> opacity color is not persisted for contexts

Not related to the update of course. The same behavior is on DEV and since it is a background color it is by design. Don't waste time on this please.

>  state of context is persisted when editing back the context

I don't see any problem in DEV about this to be honest. @MV88 @dsuren1 did you reproduce it also on DEV, if yes it is not related to the project update and, to be honest I'm wondering why it should be.

**Pull request merged**
